### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by AdamSiekierski**
As we've decided with @maciekgrzybek on Gatsby.js's discord, I could now take care of the repo. Unlike the current contributors, I have tons of time to spend to merge the PR's, do the translation reviews, etc 😄

### CODE REVIEW

**Review by maciekgrzybek — APPROVED** [review]

**Review by maciekgrzybek — APPROVED** [review]

**Review by lekterable — APPROVED** [review]

**Comment by lekterable** [comment]
thanks @AdamSiekierski , have fun! :))

**Comment by AdamSiekierski** [comment]
@lekterable I don't know if it's either our, Gatsby's or GitHub's issue, but despite being added to `CODEOWNERS` I still cannot merge PR's and don't have write access. The thing is, that now only the first person in `CODEOWNERS` is read by GitHub as the code owner, but rest of the people don't have any permissions.

What I understood from GitHub's docs, is that code owners must have write access. Gatsby's docs say that all you need to do in order to become a maintainer, is to make a PR which adds you to the `CODEOWNERS`.

Have you had a problem like this with [this](https://github.com/gatsbyjs/gatsby-pl/commit/31f789de618bd8b45d8bb6f968c4f62ab33cda4d) commit? Or should I contact with Gatsby.js team?

**Comment by lekterable** [comment]
@AdamSiekierski no clue, perhaps try contacting gatsby team. 
@kleyu can u merge PR's?

**Comment by AdamSiekierski** [comment]
@lekterable yup, I wrote an email to Gatsby via their website. Waiting for reply

**Comment by jaknas** [comment]
> @AdamSiekierski no clue, perhaps try contacting gatsby team.
> @kleyu can u merge PR's?

image

seems like I can merge it **only** after @lekterable approves the PR as according to Github he's the Codeowner.

> The thing is, that now only the first person in CODEOWNERS is read by GitHub as the code owner, but rest of the people don't have any permissions.

yeah, looks like this is the case.

**Comment by AdamSiekierski** [comment]
I think that gatsbybot should automatically add the write permissions to people who have been added to CODEOWNERS, but looks like it has been turned off for this repo.

**Comment by AdamSiekierski** [comment]
Ok, got a reply from Gatsby team. They need to do some restructuring of the docs architecture, so now they put the translations on hold. We need to wait for a while, so they set up the translation repos.

**Pull request merged**
