### PR TITLE
(sync) Resolve conflicts with gatsby-i18n-source @ 79b09bc

### PR DESCRIPTION
**Pull request by gatsbybot**
Sync conflicts with the source repo. Please update the translations based on updated source content.

<details open>
<summary>The following 41 files have conflicts:</summary><br />

* [x] docs/tutorial/using-a-theme.md
* [ ] docs/tutorial/part-zero/index.md
* [ ] docs/tutorial/part-two/index.md
* [ ] docs/tutorial/part-three/index.md
* [ ] docs/tutorial/part-seven/index.md
* [ ] docs/tutorial/part-one/index.md
* [ ] docs/tutorial/part-five/index.md
* [ ] docs/tutorial/part-eight/index.md
* [ ] docs/tutorial/index.md
* [x] docs/docs/working-with-images-in-markdown.md
* [x] docs/docs/winning-over-developers.md
* [x] docs/docs/using-graphql-playground.md
* [x] docs/docs/upgrading-node-js.md
* [x] docs/docs/unit-testing.md
* [x] docs/docs/themes/using-a-gatsby-theme.md
* [x] docs/docs/themes.md
* [x] docs/docs/theme-api.md
* [x] docs/docs/static-vs-normal-queries.md
* [x] docs/docs/sourcing-from-buttercms.md
* [x] docs/docs/routing.md
* [x] docs/docs/recipes.md
* [x] docs/docs/quick-start.md
* [x] docs/docs/query-execution.md
* [x] docs/docs/query-behind-the-scenes.md
* [x] docs/docs/preparing-for-deployment.md
* [x] docs/docs/porting-from-create-react-app-to-gatsby.md
* [x] docs/docs/path-prefix.md
* [x] docs/docs/headless-cms.md
* [x] docs/docs/gatsby-on-linux.md
* [ ] docs/docs/gatsby-cli.md
* [x] docs/docs/eslint.md
* [x] docs/docs/custom-html.md
* [x] docs/docs/bulma.md
* [x] docs/docs/building-an-e-commerce-site.md
* [x] docs/docs/babel.md
* [x] docs/docs/awesome-gatsby-resources.md
* [x] docs/docs/api-specification.md
* [x] docs/contributing/setting-up-your-local-dev-environment.md
* [x] docs/contributing/organize-a-gatsby-event.md
* [x] docs/contributing/code-of-conduct.md
* [x] docs/contributing/blog-and-website-contributions.md
</details>

Once all the commits have been fixed, mark this pull request as "Ready for review" and merge it in!

See all changes since the last sync here:

https://github.com/gatsbyjs/gatsby-i18n-source/compare/03cc9c8..79b09bc

NOTE: Do **NOT** squash-merge this pull request. The sync script requires a ref to the source repo in order to work correctly.

## Related PRs

#24 PR for syncing non-conflicting files

### CODE REVIEW

**Comment by tesseralis** [comment]
@maciekgrzybek @lekterable @matborowiak Hi everyone! Please review this PR and resolve all the merge conflicts (denoted by `<<<<<<`). I've taken the liberty to fix the conflicts in the untranslated files. I think this might have been because the previous sync was a squash-merge, which erases the history of the source commits.

**Comment by lekterable** [comment]
@tesseralis I'll take care of this today 👍

**Review by lekterable — APPROVED** [review]

**Comment by lekterable** [comment]
@tesseralis I've fixed the conflicts and reviewed the PR, let me know if I can help with anything else.

**Comment by tesseralis** [comment]
@lekterable Perfect. Thanks for your help! :)

**Pull request merged**
