### PR TITLE
Translate docs/api-files and docs/api-files-gatsby-browser

### PR DESCRIPTION
**Pull request by AleksanderSkubala**
I hope there won't be any big mistakes ;D

### CODE REVIEW

**Comment by AdamSiekierski** [comment]
I think that api-files-gatsby-browser were already submitted by another PR ;)

**Comment by maciekgrzybek** [comment]
Yeah, it looks like it was... Sorry for the confusion @AleksanderSkubala , can you pick up something else? @mbiesiad can you make sure that you're assigned to the file next time? Thanks :)

**Comment by AleksanderSkubala** [comment]
Okay I'll take another one 😉

**Comment by mbiesiad** [comment]
> Yeah, it looks like it was... Sorry for the confusion @AleksanderSkubala , can you pick up something else? @mbiesiad can you make sure that you're assigned to the file next time? Thanks :)

Sure, sorry. Updated.

**Pull request closed without merging**
